dist: xenial
sudo: false
language: cpp

matrix:
  include:
  # g++ builds
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-6
    env:
    - COMPILER="g++-6"

before_install:
  - eval "${MATRIX_EVAL}"
  - pip install --user cpp-coveralls

script:
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-6
  - export CXX=/usr/bin/g++-6
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  # Build the code and run
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - cd ..
  - ./build/bin/cpp-stlcontainer_unittests_vector
  - ./build/bin/cpp-stlcontainer_unittests_string
  - ./build/bin/cpp-stlcontainer_unittests_stack

after_success:
  - pwd
  - ls
  - coveralls --root . -E ".*external.*" -E ".*googletest.*" -E ".*CMakeFiles.*"

notifications:
email: false
